### ISSUE TITLE
左右摇杆灵敏度问题

### ISSUE THREAD

**Issue by tomh500** [eLecCap1taL/Horizon#17]
每当你进入一次地图，左右摇杆灵敏度总是1，让游戏人物自动行走，需要按下一次移动键或者手动清除灵敏度才行，如果在配置里规定ad使用snaptap，人物将无法ad移动，需要在控制台再次声明

**Comment by eLecCap1taL** [comment]
版本？

**Comment by eLecCap1taL** [comment]
capMot的灵敏度缺省应该是默认为0的才对，你确定灵敏度是1吗？

低版本没有重置joy_respondmode，可能是这个毛病。你再确认一下版本

**Comment by tomh500** [comment]
我敢保证我下载的是群文件最新版本3.4.1
